# Generated by Django 4.2.4 on 2023-08-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestro',
            name='profesion',
        ),
        migrations.AddField(
            model_name='maestro',
            name='profesion',
            field=models.ManyToManyField(to='aplicacion.materia'),
        ),
    ]
