# Generated by Django 4.2.4 on 2023-08-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_maestro_profesion_maestro_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='comision',
            field=models.ManyToManyField(to='aplicacion.materia'),
        ),
    ]
